## alertsmanager.yaml

# global:
route:
  receiver: default
receivers:
  - name: default
inhibit_rules: []
  
# BOT ERSTELLEN
# https://core.telegram.org/bots?utm_source=chatgpt.com#6-botfather
# route:
#   receiver: telegram

# receivers:
#   - name: telegram 
#     telegram_configs:
#     - bot_token: "xxxx"
#       chat_id: 12345
#       send_resolve: true
  
#   - name: email
#     email_configs:
#     - to: monitor@server.de
#       from: deine@email.de
#       smarthost: smtp.gmail.com:587
#       auth_username: "..."
#       auth_password: "..."
    
#   - name: slack