FROM python:3.12-slim

WORKDIR /app

RUN apt-get update \
    && apt-get install -y \
    ffmpeg \
    git \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen

COPY . .

CMD ["sleep", "infinity"]
