FROM python:3.12-slim

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    ffmpeg \
    git \
    curl \
    tmux \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock ./

RUN uv sync \
    --frozen \
    --no-default-groups \
    --extra lecture-worker \
    --no-editable

COPY src ./src
COPY configuration ./configuration

CMD ["sleep", "infinity"]
